#种子获取方式
# 0 = 随机 | 1 = ./plugins/MiniHunt/seeds.txt | 2 = 网络筛种
seedFrom: 0

#第1种方式的要获取的第一个种子行数
#（0为第一行，所以填在这里的行数要-1）
#每次关闭服务器都会+1
LevelSeedNum: 0

#筛种码
#自定义链接：http://www.crsuh2er0.top/fsgcn/
filterCode: 0000000000000000000000000000000000000000000000000002000200020002C

#是否在一个队伍的玩家全部掉线时直接结束游戏
endWhenAllLeave: false

#是否在上述情况下判断胜者
judgeWinnerWhenLeaveEnd: true

#玩家断开连接后的可重连时间（秒）
reJoinTime: 180

# 是否开启友伤
FriendsHurt: false

#第零阶梯玩家数量（同时也是最小玩家数量）
#（大于等于该数量Runner会设置对应阶梯数量，下同）
#如L0Player=2 L0Hunter=1即在总玩家达到2及以上的时候，猎人数为1）
L0Player: 2

#第零阶梯逃亡者数量
L0Runner: 1

#第一阶梯玩家数量
L1Player: 6

#第一阶梯逃亡者数量
L1Runner: 2

#第二阶梯玩家数量
L2Player: 12

#第二阶梯逃亡者数量
L2Runner: 3

#第三阶梯玩家数量（同时也是最大玩家数量）
L3Player: 16

#第三阶梯逃亡者数量
L3Runner: 4

#是否允许选择队伍
SelectTeam: true

#是否开局解锁指南针
CompassUnlocked: true

#是否结束游戏自动踢出所有玩家
AutoKick: true

#逃亡者X轴偏移（Basic为基础偏移，Random为随机值）
#实际偏移量为（Basic+Random）
#如XBasic: 10 XRandom: 20 则实际偏移量为10+(0~20)=10~30中取一个随机数
XBasic: 5
XRandom: 10

#逃亡者Y轴偏移（Basic为基础偏移，Random为随机值）
#计算原理同上
YBasic: 5
YRandom: 10

#逃亡者警告距离
#建议合理调整方便猎人生存
WarnDistance: 50
HunterWarnDistance: 50

#开局倒计时时长
Countdown: 10

#逃亡者警告消息(%wd是警告距离就是上面那个，%d是当前距离）
WarnDistanceSafe: "%sM 内未检测到猎人"
WarnDistanceClose: "警告! 猎人正在靠近! 当前距离： %s 个方块"
HunterWarnDistanceClose: "提示! 在 %d 个方块内躲藏着逃亡者! "

#首次进入地狱提供抗火时长
FireResistanceTime: 30

#服务器名称（实际上也就结束统计的时候显示一下）
ServerName: "Minecraft"

#游戏名称（实际上也同样就结束统计的时候显示一下）
ServerGame: "猎人游戏"

#观战玩家名字前缀
ObserverName: "[吃瓜]"

#追杀者玩家名字前缀
HunterName: "[猎人]"

#逃亡者玩家名字前缀
RunnerName: "[逃亡者]"

#等待中玩家名字前缀
WaitingName: "[等待中]"

#统计展示的击杀龙的玩家
DragonKiller: "屠龙勇士"

#统计展示的击杀逃亡者的玩家
RunnerKiller: "最佳猎人"

#统计展示的对任何实体输出伤害最多的玩家
DamageOutPut: "最佳输出"

#统计展示的受到伤害最多的玩家
DamageReceive: "最惨靶子"

#统计展示的对敌方输出最多的玩家
TeamKiller: "超神选手"

#统计展示的对敌方输出最多的玩家
TeamEndDragon: "屠龙勇士"

#统计展示的移动距离最多的玩家
WalkMaster: "大旅行者"

#统计展示的跳跃次数最多的玩家
JumpMaster: "蹦迪大师"

#统计展示结束后的结语
EndText1: "感谢游玩"
EndText2: "Thanks for playing!"
