name: MiniHunt
version: 3.8
main: net.mcxk.minihunt.MiniHunt
authors: [ MossCG, LingMuQingYu, Crsuh2er0 ]
website: https://github.com/MiaoCraft/MiniHunt
api-version: 1.16
loadbefore:
  - MiniHunt
softdepend:
  - AdvancedReplay

commands:
  minihunt:
    description: 猎人游戏指令
    aliases:
      - mh
    usage: |
      /mh [about|hunter|runner|rstcd|players|start|want|help]

permissions:
  minihunt.admin:
    description: 猎人游戏管理权限
