name: HJYHunt
version: 3.4
main: net.mcxk.hjyhunt.HJYHunt
authors: [ MossCG, LingMuQingYu, Crsuh2er0 ]
website: https://github.com/MiaoCraft/HJYHunt
api-version: 1.16
softdepend:
  - AdvancedReplay

commands:
  hjyhunt:
    description: 猎人游戏指令
    usage: |
      /<command> [about|hunter|runner|rstcd|players|start|want|help]
